services:
  hhvm:
    container_name: theodore-printf-state-machine-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48563:10641
